// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef btreefluid_h
#define btreefluid_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
class CustomWindow : public Fl_Double_Window {
public:
	CustomWindow(int w, int h, const char* t);
	void draw();
};
#endif
